### ISSUE TITLE
Allow version resolution to be forced

### ISSUE THREAD

**Issue by Tyrannoseanus** [toolebox-io/gradle-git-versioner#17]
This comment https://github.com/toolebox-io/gradle-git-versioner/issues/13#issuecomment-621063653 links to another plugin that has "active versioning" rather than "passive versioning". Meaning that in the gradle file you specifically apply the version configuration which will set the version at that point. This plugin currently relies on Gradle phases and project evaluation to populate the version, and will only apply the version after the project has been evaluated. 

This is usually fine as the majority of configuration that relies on version can be done after project evaluation, but this is not always obvious and it would be useful to have a way to force this to happen at a certain point in the build script. 

This could be as simple as adding a `forceResolution` method to the configuration that would calculate and apply the version to the project. This way we could keep the existing behaviour but also allow consumers to force version to be resolved if they find they need it earlier than it would usually be available.

**Comment by AnakinPt** [comment]
I need this urgently, because I can't integrate this plugin with the com.plantir.docker plugin. I need to add tasks using this:
`
docker {
        tag 'local', "${project.name}:latest"
        tag 'localVersion', "${project.name}:${project.version}"
        tag 'awsLatest', "ecr/${project.name}:latest"
        tag 'awsVersion', "ecr/${project.name}:${project.version}"
        name "${project.name}"
        dockerfile file("Dockerfile")
}
`
and if I just put those tag lines inside the afterEvaluate the docker plugin won't know them when run the task. But if I put everything, I get a different error, like docker not being ready. Of course, not having the afterEvaluate I get versions 'unspecified'

**Comment by Tyrannoseanus** [comment]
Closed in #18 

@AnakinPt please try this out now and let me know how you get on.

**Comment by Tyrannoseanus** [comment]
This is release 1.5.0 by the way

**Comment by AnakinPt** [comment]
Thank you. This is working perfectly.
