### ISSUE TITLE
No support for maven snapshot style versions

### ISSUE THREAD

**Issue by MightyLampshade** [toolebox-io/gradle-git-versioner#4]
The git-versioner has no support for maven snapshot versions when writing "development" code. It would be good if it was an optional setting on the versioner so that both methods could be used.

[Maven Getting Started: What is a SNAPSHOT version](https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version)

**Comment by Tyrannoseanus** [comment]
This should have been fixed by #9, you should be able to use the pattern `%M.%m(-SNAPSHOT) to get maven style snapshotting.
