### ISSUE TITLE
Change separator between patch number and commit count

### ISSUE THREAD

**Issue by dnnrly** [toolebox-io/gradle-git-versioner#7]
Assuming your project is at version `1.2.3` commits after the last patch change append `.N` where `N` is the number of commits after the patch update.

It would be good if we could change the separator from `.` to some arbitrary value so that this update becomes more meaningful. For example:

```
versioner {
 buildSeparator = '-SNAPSHOT-'
}
```

Would give versions with `1.2.3-SNAPSHOT-14`.

It also allows for the possibility of inserting other information at build time, such as the branch name. For example:
```
versioner {
 buildSeparator = "-${project.getProperty('branch-name')}-"
}
```

When gradle is invoked as following:
```
export BRANCH=$(git rev-parse --abbrev-ref HEAD | tr -d '\n' | sed -e 's/\//-/g' -e 's/feature/ft/g')
./gradlew -Pbranch-name=${BRANCH} -q printVersion
```

When run in a branch with name `feature/wowee`, you would get the following output:
`1.2.3-ft-wowee-14`

**Comment by Tyrannoseanus** [comment]
This should have been fixed by #9, which ought to handle this kind of flexibility. 

Please re-open if this does not meet your needs
